[package]
name = "puppy"
version = "0.1.0"
edition = "2024"

[dependencies]
camino = "1.2.2"
chumsky = "0.13.0"
clap = { version = "4.6.1", features = ["derive"] }
codespan-reporting = "0.13.1"
lasso = { version = "0.7.3", features = ["multi-threaded"] }
ordered-float = "5.3.0"

[lints.rust]
missing_copy_implementations = "warn"
missing_debug_implementations = "warn"
unsafe_code = "deny"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
alloc_instead_of_core = "warn"
std_instead_of_core = "warn"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
